openapi: "3.1.0"
info:
  title: "ktor_sample API"
  description: "ktor_sample API"
  version: "1.0.0"
servers:
- url: "https://ktor_sample"
paths:
  /:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "New User register successfully!"
  /users:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/User"
              examples:
                Example#1:
                  description: ""
                  value: []
components:
  schemas:
    LoginDTO:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
      required:
      - "username"
      - "password"
    User:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
        email:
          type: "string"
        age:
          type: "integer"
          format: "int32"
      required:
      - "username"
      - "password"
      - "email"